name: post

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      BSKY_USER: ${{ secrets.BSKY_USER }}
      BSKY_PSWD: ${{ secrets.BSKY_PSWD }}
      
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - run: go run main.go
